import { MasterData } from "../models/MasterData";

export const defaultEvent: MasterData[] = [
    {
        id: 39200,
        groupId: 'default-group',
        projectId: 39200,
        imageUrl: '/images/no-image.jpg',
        eventName: '陸人へ',
        groupName: '伊藤 汰海',
        catchphrase: '継続王',
        eventContent: '半年間お疲れさま！異例の制作への転局で、名前覚えたり、技術覚えたり大変だったと思います。そのくせに継続として当然のごとく扱ってしまっていたのは本当に申し訳ないです。AIをうまく使いながら、ほとんど1人でプレサイトを作ってくれたときは、参団ツールが山場だった俺はめっちゃ助かりました。新規合流後も、自分が覚えたての技術も短期間で新規に教えられるまで成長したのは今でも信じられないです。参団と文化も大きく違う中で、ここまで頑張ってくれて本当にありがとう。陸人がいなかったら全てが回りませんでした。めちゃ感謝です。',
        genre: '',
        icons: [],
        location: '和泉ラーニングスクエア 食堂2階',
        eventDate: '11月4日 片付け日',
        xAccount: '',
        instagramAccount: '',
        tiktokAccount: '',
        youtubeAccount: '',
        homepageUrl: '',
        searchKeywords: '',
        createdAt: new Date(),
        updatedAt: new Date(),
        type: 'default',
        enableShooting: false,
        ticket: '',
        foodIcons: [],
        otherIcons: [],
        menuItems: [],
        qrcode: '',
    },
    {
        id: 39100,
        groupId: 'default-group',
        projectId: 39100,
        imageUrl: '/images/no-image.jpg',
        eventName: '大知へ',
        groupName: '伊藤 汰海',
        catchphrase: '王',
        eventContent: '半年間お疲れ様！Webに配属されてから、高い成長欲と理解力でめっちゃ頑張ってくれました。新規のうちから対決企画の投票フォームを作り上げて、滞りなく投票を終えられたのは前代未聞の快挙です。そしてその技術力を他の新規に共有し、部門全体の技術力の底上げにも貢献してくれたからこそ、本祭暇で終えられるほどのスピード感で実装を進めることができたのだと思います。難しい概念にも触れなければならなく、プログラミングの挫折率が9割を超える中で、最後まで部門全員がついてこれたのは大知のおかげです。本当にありがとう！来年以降も頑張ってください！',
        genre: '',
        icons: [],
        location: '和泉ラーニングスクエア 食堂2階',
        eventDate: '11月4日 片付け日',
        xAccount: '',
        instagramAccount: '',
        tiktokAccount: '',
        youtubeAccount: '',
        homepageUrl: '',
        searchKeywords: '',
        createdAt: new Date(),
        updatedAt: new Date(),
        type: 'default',
        enableShooting: false,
        ticket: '',
        foodIcons: [],
        otherIcons: [],
        menuItems: [],
        qrcode: '',
    },
    {
        id: 39101,
        groupId: 'default-group',
        projectId: 39101,
        imageUrl: '/images/no-image.jpg',
        eventName: '映奈へ',
        groupName: '伊藤 汰海',
        catchphrase: '乃木坂王',
        eventContent: '半年間お疲れ様！説明会の時に、Webに興味があると言ってくれたのは本当に嬉しかったです。とにかく人手が足りなかった当時は本当に希望の光でした。実際にコードを書いた時はかなり苦戦もしただろうけど、めげずに取り組み続け、最終的には誰よりも下層ページをめっちゃ早く仕上げてくれるようになったのは感動しています。えなが完璧に下層を量産してくれたからこそ、俺は企画検索に集中することができました。企画検索のデザインもめっちゃかわいいです！素敵なデザインのコードを書かせてくれてありがとう！来年以降も頑張ってください！',
        genre: '',
        icons: [],
        location: '和泉ラーニングスクエア 食堂2階',
        eventDate: '11月4日 片付け日',
        xAccount: '',
        instagramAccount: '',
        tiktokAccount: '',
        youtubeAccount: '',
        homepageUrl: '',
        searchKeywords: '',
        createdAt: new Date(),
        updatedAt: new Date(),
        type: 'default',
        enableShooting: false,
        ticket: '',
        foodIcons: [],
        otherIcons: [],
        menuItems: [],
        qrcode: '',
    },
    {
        id: 39102,
        groupId: 'default-group',
        projectId: 39102,
        imageUrl: '/images/no-image.jpg',
        eventName: '史織へ',
        groupName: '伊藤 汰海',
        catchphrase: 'キャッチ',
        eventContent: '半年間お疲れ様！本サイトの作成に入った時に、誰よりも真っ先にいろんなページやコンポーネントに取り組んでくれたのを覚えています。Githubの使い方など、技術伝達ではあまりちゃんとやらなかった部分も、自分でNotionを参考にしながらバリバリ進めてくれていたのが頼もしかったです。終盤のキャンパスマップのページでも新しいことがたくさんだったと思うけど、たくさん考えて頑張ってくれてありがとう！そんなしおりの姿があったからこそ、他の新規も「自分も頑張ろう」と思えたのだと思います。そんな頼もしい背中を来年も見せて、新規を引っ張っていってほしいです！。来年以降も頑張ってください！',
        genre: '',
        icons: [],
        location: '和泉ラーニングスクエア 食堂2階',
        eventDate: '11月4日 片付け日',
        xAccount: '',
        instagramAccount: '',
        tiktokAccount: '',
        youtubeAccount: '',
        homepageUrl: '',
        searchKeywords: '',
        createdAt: new Date(),
        updatedAt: new Date(),
        type: 'default',
        enableShooting: false,
        ticket: '',
        foodIcons: [],
        otherIcons: [],
        menuItems: [],
        qrcode: '',
    },
    {
        id: 39103,
        groupId: 'default-group',
        projectId: 39103,
        imageUrl: '/images/no-image.jpg',
        eventName: '紗来へ',
        groupName: '伊藤 汰海',
        catchphrase: '',
        eventContent: '半年間お疲れ様！さらの明るい性格で、部門の雰囲気もめっちゃ明るくしてくれてありがとう！新規面談の時にデザインをやりたい！って話してくれたからデザインを任せました！企画検索のデザインは、えなが作ったものと統一感を出さなきゃいけないことで、かなり制約がある中だったけど、可愛いメニューのデザインをはじめとても可愛いデザインを作ってくれてありがとう！下層ページ作成でも積極的に手を挙げてくれて、本当に助かりました。さらはコードも書けて、雰囲気も盛り上げる天才なので、来年の部門も盛り上げていってください！来年以降も頑張ってください！',
        genre: '',
        icons: [],
        location: '和泉ラーニングスクエア 食堂2階',
        eventDate: '11月4日 片付け日',
        xAccount: '',
        instagramAccount: '',
        tiktokAccount: '',
        youtubeAccount: '',
        homepageUrl: '',
        searchKeywords: '',
        createdAt: new Date(),
        updatedAt: new Date(),
        type: 'default',
        enableShooting: false,
        ticket: '',
        foodIcons: [],
        otherIcons: [],
        menuItems: [],
        qrcode: '',
    },
    {
        id: 39104,
        groupId: 'default-group',
        projectId: 39104,
        imageUrl: '/images/no-image.jpg',
        eventName: '誠一朗へ',
        groupName: '伊藤 汰海',
        catchphrase: 'うんちく王',
        eventContent: '半年間お疲れ！中野キャンパスなのに、和泉の新歓に来てくれて、そこでめっちゃ話せたの嬉しかったです。毎年Webがあまり人気がないのもあって、Webに来たい言ってくれる人はとても貴重でした。新規唯一のサイト作成経験者ということで、かなり期待していました。Next.jsということで今まで触っていたものとは少し違っていたかもしれないけれど、それまでの知識とうまく組み合わせて、周りの新規を助けてくれたのは、継続の人手が足りていない中でとても助かりました。来年は新規にも教える立場になるので、誠一朗の知識でWeb部門を引っ張っていってください！来年以降も頑張ってください！',
        genre: '',
        icons: [],
        location: '和泉キャンパス 食堂2階',
        eventDate: '11月4日 片付け日',
        xAccount: '',
        instagramAccount: '',
        tiktokAccount: '',
        youtubeAccount: '',
        homepageUrl: '',
        searchKeywords: '',
        createdAt: new Date(),
        updatedAt: new Date(),
        type: 'default',
        enableShooting: false,
        ticket: '',
        foodIcons: [],
        otherIcons: [],
        menuItems: [],
        qrcode: '',
    },
    {
        id: 39105,
        groupId: 'default-group',
        projectId: 39105,
        imageUrl: '/images/no-image.jpg',
        eventName: '魁凰へ',
        groupName: '伊藤 汰海',
        catchphrase: '雰囲気王',
        eventContent: '半年間お疲れ様！最初の局での自己紹介で、Webに入りたいって言ってくれたインパクトは大きかったです。そのとても明るい性格から、繁忙期でもWebの雰囲気を保ち続けてくれたのは本当に感謝しています。技術的な面では、別の団体でもサイト制作を学んでいて、そこと使っている技術の差に戸惑っていたけど、忙しい中でもなんだかんだ与えた仕事にはきちんと取り組んでくれてありがとう！来年もその明るさでWeb部門を盛り上げていってください！来年以降も頑張ってください！',
        genre: '',
        icons: [],
        location: '和泉ラーニングスクエア 食堂2階',
        eventDate: '11月4日 片付け日',
        xAccount: '',
        instagramAccount: '',
        tiktokAccount: '',
        youtubeAccount: '',
        homepageUrl: '',
        searchKeywords: '',
        createdAt: new Date(),
        updatedAt: new Date(),
        type: 'default',
        enableShooting: false,
        ticket: '',
        foodIcons: [],
        otherIcons: [],
        menuItems: [],
        qrcode: '',
    },
    {
        id: 39300,
        groupId: 'default-group',
        projectId: 39300,
        imageUrl: '/images/no-image.jpg',
        eventName: '翔央さんへ',
        groupName: '伊藤 汰海',
        catchphrase: 'ミーム王',
        eventContent: 'お疲れ様でした！2年目の付き合いとなった今年ですが、Webのキャパが本当にやばい時に、いつも完璧なクオリティで制作物を仕上げてくれたのはまじで助かりました。去年翔央さんが背負っていたWeb部門の重責、サイトの可愛いデザインを今年引き継げるか不安でした。それでも',
        genre: '',
        icons: [],
        location: '和泉ラーニングスクエア 食堂2階',
        eventDate: '11月4日 片付け日',
        xAccount: '',
        instagramAccount: '',
        tiktokAccount: '',
        youtubeAccount: '',
        homepageUrl: '',
        searchKeywords: '',
        createdAt: new Date(),
        updatedAt: new Date(),
        type: 'default',
        enableShooting: false,
        ticket: '',
        foodIcons: [],
        otherIcons: [],
        menuItems: [],
        qrcode: '',
    },
    {
        id: 39301,
        groupId: 'default-group',
        projectId: 39301,
        imageUrl: '/images/no-image.jpg',
        eventName: '彩羽さんへ',
        groupName: '伊藤 汰海',
        catchphrase: '美容師王',
        eventContent: 'メッセージ',
        genre: '',
        icons: [],
        location: '和泉ラーニングスクエア 食堂2階',
        eventDate: '11月4日 片付け日',
        xAccount: '',
        instagramAccount: '',
        tiktokAccount: '',
        youtubeAccount: '',
        homepageUrl: '',
        searchKeywords: '',
        createdAt: new Date(),
        updatedAt: new Date(),
        type: 'default',
        enableShooting: false,
        ticket: '',
        foodIcons: [],
        otherIcons: [],
        menuItems: [],
        qrcode: '',
    },
    {
        id: 39302,
        groupId: 'default-group',
        projectId: 39302,
        imageUrl: '/images/no-image.jpg',
        eventName: '雄大さんへ',
        groupName: '伊藤 汰海',
        catchphrase: '横揺れ王',
        eventContent: 'メッセージ',
        genre: '',
        icons: [],
        location: '和泉ラーニングスクエア 食堂2階',
        eventDate: '11月4日 片付け日',
        xAccount: '',
        instagramAccount: '',
        tiktokAccount: '',
        youtubeAccount: '',
        homepageUrl: '',
        searchKeywords: '',
        createdAt: new Date(),
        updatedAt: new Date(),
        type: 'default',
        enableShooting: false,
        ticket: '',
        foodIcons: [],
        otherIcons: [],
        menuItems: [],
        qrcode: '',
    }
]