import { MasterData } from "../models/MasterData";

export const defaultEvent: MasterData[] = [
    {
        id: 39200,
        groupId: 'default-group',
        projectId: 39200,
        imageUrl: '/images/no-image.jpg',
        eventName: '陸人へ',
        groupName: '伊藤 汰海',
        catchphrase: 'キャッチ',
        eventContent: 'メッセージ',
        genre: '',
        icons: [],
        location: '',
        eventDate: '11月4日 片付け日',
        xAccount: '',
        instagramAccount: '',
        tiktokAccount: '',
        youtubeAccount: '',
        homepageUrl: '',
        searchKeywords: '',
        createdAt: new Date(),
        updatedAt: new Date(),
        type: 'default',
        enableShooting: false,
        ticket: '',
        foodIcons: [],
        otherIcons: [],
        menuItems: [],
        qrcode: '',
    },
    {
        id: 39100,
        groupId: 'default-group',
        projectId: 39100,
        imageUrl: '/images/no-image.jpg',
        eventName: '大知へ',
        groupName: '伊藤 汰海',
        catchphrase: 'キャッチ',
        eventContent: 'メッセージ',
        genre: '',
        icons: [],
        location: '',
        eventDate: '11月4日 片付け日',
        xAccount: '',
        instagramAccount: '',
        tiktokAccount: '',
        youtubeAccount: '',
        homepageUrl: '',
        searchKeywords: '',
        createdAt: new Date(),
        updatedAt: new Date(),
        type: 'default',
        enableShooting: false,
        ticket: '',
        foodIcons: [],
        otherIcons: [],
        menuItems: [],
        qrcode: '',
    },
    {
        id: 39101,
        groupId: 'default-group',
        projectId: 39101,
        imageUrl: '/images/no-image.jpg',
        eventName: '映奈へ',
        groupName: '伊藤 汰海',
        catchphrase: 'キャッチ',
        eventContent: 'メッセージ',
        genre: '',
        icons: [],
        location: '',
        eventDate: '11月4日 片付け日',
        xAccount: '',
        instagramAccount: '',
        tiktokAccount: '',
        youtubeAccount: '',
        homepageUrl: '',
        searchKeywords: '',
        createdAt: new Date(),
        updatedAt: new Date(),
        type: 'default',
        enableShooting: false,
        ticket: '',
        foodIcons: [],
        otherIcons: [],
        menuItems: [],
        qrcode: '',
    },
    {
        id: 39102,
        groupId: 'default-group',
        projectId: 39102,
        imageUrl: '/images/no-image.jpg',
        eventName: '史織へ',
        groupName: '伊藤 汰海',
        catchphrase: 'キャッチ',
        eventContent: 'メッセージ',
        genre: '',
        icons: [],
        location: '',
        eventDate: '11月4日 片付け日',
        xAccount: '',
        instagramAccount: '',
        tiktokAccount: '',
        youtubeAccount: '',
        homepageUrl: '',
        searchKeywords: '',
        createdAt: new Date(),
        updatedAt: new Date(),
        type: 'default',
        enableShooting: false,
        ticket: '',
        foodIcons: [],
        otherIcons: [],
        menuItems: [],
        qrcode: '',
    },
    {
        id: 39103,
        groupId: 'default-group',
        projectId: 39103,
        imageUrl: '/images/no-image.jpg',
        eventName: '紗更へ',
        groupName: '伊藤 汰海',
        catchphrase: 'キャッチ',
        eventContent: 'メッセージ',
        genre: '',
        icons: [],
        location: '',
        eventDate: '11月4日 片付け日',
        xAccount: '',
        instagramAccount: '',
        tiktokAccount: '',
        youtubeAccount: '',
        homepageUrl: '',
        searchKeywords: '',
        createdAt: new Date(),
        updatedAt: new Date(),
        type: 'default',
        enableShooting: false,
        ticket: '',
        foodIcons: [],
        otherIcons: [],
        menuItems: [],
        qrcode: '',
    },
    {
        id: 39104,
        groupId: 'default-group',
        projectId: 39104,
        imageUrl: '/images/no-image.jpg',
        eventName: '誠一朗へ',
        groupName: '伊藤 汰海',
        catchphrase: 'キャッチ',
        eventContent: 'メッセージ',
        genre: '',
        icons: [],
        location: '和泉キャンパス 食堂2階',
        eventDate: '11月4日 片付け日',
        xAccount: '',
        instagramAccount: '',
        tiktokAccount: '',
        youtubeAccount: '',
        homepageUrl: '',
        searchKeywords: '',
        createdAt: new Date(),
        updatedAt: new Date(),
        type: 'default',
        enableShooting: false,
        ticket: '',
        foodIcons: [],
        otherIcons: [],
        menuItems: [],
        qrcode: '',
    },
    {
        id: 39105,
        groupId: 'default-group',
        projectId: 39105,
        imageUrl: '/images/no-image.jpg',
        eventName: '魁凰へ',
        groupName: '伊藤 汰海',
        catchphrase: 'キャッチ',
        eventContent: 'メッセージ',
        genre: '',
        icons: [],
        location: '',
        eventDate: '11月4日 片付け日',
        xAccount: '',
        instagramAccount: '',
        tiktokAccount: '',
        youtubeAccount: '',
        homepageUrl: '',
        searchKeywords: '',
        createdAt: new Date(),
        updatedAt: new Date(),
        type: 'default',
        enableShooting: false,
        ticket: '',
        foodIcons: [],
        otherIcons: [],
        menuItems: [],
        qrcode: '',
    }
]